export const tours = [
  {
    slug: "lhasa-classic",
    name: "Lhasa Classic Journey",
    country: "Tibet",
    days: "5 days",
    price: "$1,290",
    difficulty: "Easy–Moderate",
    lat: 29.652,
    lng: 91.172,
  },
  {
    slug: "lhasa-everest-base-camp",
    name: "Lhasa to Everest Base Camp",
    country: "Tibet",
    days: "8 days",
    price: "$1,890",
    difficulty: "Moderate",
    lat: 28.193,
    lng: 86.829,
  },
  {
    slug: "lhasa-shigatse-gyantse",
    name: "Lhasa, Gyantse & Shigatse",
    country: "Tibet",
    days: "7 days",
    price: "$1,590",
    difficulty: "Easy–Moderate",
    lat: 29.267,
    lng: 88.881,
  },
  {
    slug: "tibet-high-plateau",
    name: "Tibet High Plateau",
    country: "Tibet",
    days: "12 days",
    price: "$2,190",
    difficulty: "Moderate",
    lat: 29.65,
    lng: 91.1,
  },
  {
    slug: "kailash-mansarovar-journey",
    name: "Kailash & Mansarovar Journey",
    country: "Tibet",
    days: "15 days",
    price: "$2,890",
    difficulty: "Moderate",
    lat: 31.0675,
    lng: 81.3119,
  },
  {
    slug: "kailash-kora",
    name: "Mount Kailash Kora",
    country: "Tibet",
    days: "13 days",
    price: "$2,690",
    difficulty: "Challenging",
    lat: 31.0675,
    lng: 81.3119,
  },
  {
    slug: "namtso-lake",
    name: "Lhasa & Namtso Lake",
    country: "Tibet",
    days: "7 days",
    price: "$1,690",
    difficulty: "Moderate",
    lat: 30.718,
    lng: 90.643,
  },
  {
    slug: "tibet-photography",
    name: "Tibet Photography Journey",
    country: "Tibet",
    days: "10 days",
    price: "$2,390",
    difficulty: "Moderate",
    lat: 29.652,
    lng: 91.172,
  },
  {
    slug: "tibet-culture-monasteries",
    name: "Tibet Culture & Monasteries",
    country: "Tibet",
    days: "9 days",
    price: "$1,990",
    difficulty: "Easy–Moderate",
    lat: 29.652,
    lng: 91.172,
  },
] as const;

export type Tour = (typeof tours)[number];

export function getTour(slug: string) {
  return tours.find((t) => t.slug === slug);
}
